### ISSUE TITLE
Functional requirements：Mouse button visualization

### ISSUE THREAD

**Issue by iamaweiawei** [mulaRahul/keyviz#101]
**Is your feature request related to a problem? Please describe.**
Sometimes keyboard shortcuts need to be combined with mouse buttons for some function, left or right, and even some software requires mouse wheel buttons; so I want you to add an additional function of mouse visualization

**Describe the solution you'd like**
My vision is to add this feature to your current keyboard visualization, but the area of mouse visualization, how to fix a position at will, just need a switch: fixed or unlocked; Mouse UI, you do not need a variety of colors, only need black and white;

**Describe alternatives you've considered**
I've been using this software before: SpotOnTheMouse, the second style, mouse visualization, but the UI is too old and unattractive; if you're adding this feature, I'm sure your product is perfect and beautiful, i love your UI design

**Comment by mulaRahul** [comment]
That planned right [here](https://github.com/mulaRahul/keyviz/discussions/36#discussioncomment-4352731)!

**Comment by iamaweiawei** [comment]
I didn't know there was a need to vote. It seems everyone has a need

**Comment by mulaRahul** [comment]
Added with [v2.0.0a](https://github.com/mulaRahul/keyviz/releases/tag/v2.0.0a).
