### ISSUE TITLE
有几率出现“F22”问题

### ISSUE THREAD

**Issue by xueojssu** [mulaRahul/keyviz#102]
**Describe the bug**
接下来打的字可以正常显示按键，但是“F22”它不会自动消失并且状态是按下去的

**Version**: v0.x.x

**To Reproduce**

**Expected behavior**

**Screenshots**
不知道怎么添加截图

**Desktop (please complete the following information):**
 - Windows 11

**Additional context**

**Comment by mulaRahul** [comment]
Hello @xueojssu, can you reproduce the same with [v2.0.0a](https://github.com/mulaRahul/keyviz/releases/tag/v2.0.0a)?

**Comment by mulaRahul** [comment]
Will be further tracked in #136.
