### ISSUE TITLE
Hope keyviz supports custom button size!

### ISSUE THREAD

**Issue by fengyeyer** [mulaRahul/keyviz#116]
**Is your feature request related to a problem? Please describe.**
Why can't it support custom button display size? I always feel the buttons are too big (even the smallest 32px)

**Describe the solution you'd like**
I want keyviz to support custom key size!

**Comment by ruslooob** [comment]
@mulaRahul, can you edit this issue? There should be only 2 lines in it.

**Comment by mulaRahul** [comment]
Added with [v2.0.0a](https://github.com/mulaRahul/keyviz/releases/tag/v2.0.0a).
