### ISSUE TITLE
Virus total report not clean

### ISSUE THREAD

**Issue by 8ctopus** [mulaRahul/keyviz#119]
**Describe the bug**

The portable version is tagged by 6 antiviruses in virustotal.

https://www.virustotal.com/gui/file/2ad3c462b44e0bd7ef150fdc875d0c12d606f0387e843422ec0312eecf29054a

**Version**: v1.0.6 portable

**Comment by Chris1320** [comment]
Could it be a false positive? It might be falsely detected as a keylogger.

**Comment by damywise** [comment]
Definitely got flagged as a keylogger
![image](https://github.com/mulaRahul/keyviz/assets/25608913/da0b709d-cdfd-4053-b38b-39472d4d249e)

**Comment by damywise** [comment]
I honestly wouldn't worry even a bit about any of those.
1. That's a side effect of packing the app into a single exe using enigma virtual box
2. Same thing and normal for some fields.
3. No idea where this could have come from lol there's nothing in the code.

Also, in case you haven't noticed, the app doesn't connect to the internet at all.

Though if people are very concerned, they're free to build/run/compile the program themselves. I personally have modified some things locally in the past to fix some bugs.

**Comment by mediculus** [comment]
I see; as I mentioned, I'm not knowledgable at all but was definitely concerned when a scan flagged some things, so I wouldn't really know the first thing on whether or not those pickups are "intended" or not.

Much appreciated for the responses and explanations!

**Comment by mulaRahul** [comment]
Now you download Keyviz from [Microsoft Store](https://apps.microsoft.com/detail/Keyviz/9phzpj643p7l?mode=direct).
