### ISSUE TITLE
May change an new flattened icon

### ISSUE THREAD

**Issue by JohnsonSii** [mulaRahul/keyviz#127]
The tray icon in the bottom right corner of Windows is very small. I hope to replace it with a flattened icon to look more beautiful.

**Comment by mulaRahul** [comment]
Indeed! 
I've tried re-creating the icon and came up with this -

**Visualizer on**
![visualizer-on](https://user-images.githubusercontent.com/96373135/233275761-da1ed14e-b5fc-4b34-92dd-ca383ac3e8af.png)


**Visualizer off**
![visualizer-off](https://user-images.githubusercontent.com/96373135/233275772-44782440-5226-4371-99a3-f014498466aa.png)


Do let me know about your thoughts!

**Comment by mulaRahul** [comment]
Added with [v2.0.0a](https://github.com/mulaRahul/keyviz/releases/tag/v2.0.0a).
