### ISSUE TITLE
MacOS release

### ISSUE THREAD

**Issue by ImBIOS** [mulaRahul/keyviz#128]
### Discussed in https://github.com/mulaRahul/keyviz/discussions/12

<div type='discussions-op-text'>

<sup>Originally posted by **sergeysova** August  2, 2022</sup>
The design looks beautiful. What about to release for macOS users?</div>

**Comment by mulaRahul** [comment]
Added in [v2.0.0a](https://github.com/mulaRahul/keyviz/releases/tag/v2.0.0a).
