### ISSUE TITLE
Request to include basic build instructions

### ISSUE THREAD

**Issue by nmstoker** [mulaRahul/keyviz#145]
I appreciate that many people will just want to use the compiled version but it would be great to see some build instructions so that users could build it themselves. I had a look around the repo but couldn't see anything regarding this.

Ideally a brief section could be added to the README, with a few basic pointers on how to build it. If not in the README, perhaps a stand alone document?

This would help people who aren't fully sure if they can trust the pre-built version (eg those using it in a work environment ).

I did see a make file here, https://github.com/mulaRahul/keyviz/tree/main/windows but my experience with Dart is limited so basic advice would get me heading in the right direction.

Many thanks for the repo @mulaRahul - it's really high quality and your video is excellent (very clear)

**Comment by mulaRahul** [comment]
True that, I didn't consider adding build instructions for the project. Thanks for getting my attention to the same! 

Added the same with e9e22b83883657ce884bc92842821e8ae47ea1d7.

**Comment by nmstoker** [comment]
That's fantastic! Thanks a lot for doing that (and so quickly!)
Will be giving it a go soon 👍
