### ISSUE TITLE
Support smaller font size

### ISSUE THREAD

**Issue by ruslooob** [mulaRahul/keyviz#147]
At the moment, there are only 6 font size options in the application, and all of them do not suit me. You need to add the ability to specify a smaller font. Maybe so that the user can enter it manually

![image](https://github.com/mulaRahul/keyviz/assets/76997293/fef1e8f7-a80a-48b7-8be1-69b96698c54f)

**Comment by mulaRahul** [comment]
Hello @ruslooob, the same is been tracked in #116.
