### ISSUE TITLE
按键文字显示不全.

### ISSUE THREAD

**Issue by QQ804218** [mulaRahul/keyviz#157]
**Describe the bug**

**Version**: v2.0

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11

**Additional context**

https://github.com/mulaRahul/keyviz/assets/67571282/7e8ffc7b-4949-41be-a929-5f4df0875db4

按键文字显示不全.

**Comment by mulaRahul** [comment]
Fixed with 7fbb37ad0edfd9444221f5845c2f91de8af8f56d.
