### ISSUE TITLE
[Feature Request] `space` key improve & keep presets in v1

### ISSUE THREAD

**Issue by Cierra-Runis** [mulaRahul/keyviz#158]
1. The `space` key is plain, which is not pretty enough. It's better to add a line just like below. 
![image](https://github.com/mulaRahul/keyviz/assets/29329988/4e9aa598-4f1f-45e0-8ad3-ac1ef28707f5)
2. The presets in v1 is also great, it's better to keep them in v2.

**Comment by mulaRahul** [comment]
By 

> The presets in v1 is also great, it's better to keep them in v2.

do you mean the predefined color combinations?

**Comment by Cierra-Runis** [comment]
> By
> 
> > The presets in v1 is also great, it's better to keep them in v2.
> 
> do you mean the predefined color combinations?

This one.
![image](https://github.com/mulaRahul/keyviz/assets/29329988/587a7d99-b21c-4878-8048-5996dc5a60dc)

**Comment by mulaRahul** [comment]
You could achieve the same with the current **plastic** style and **gradient** fill type, not exact but close.

**Comment by Cierra-Runis** [comment]
OK~

**Comment by mulaRahul** [comment]
Added "space" text from [v2.0.0a2](https://github.com/mulaRahul/keyviz/releases/tag/v2.0.0a2)
