### ISSUE TITLE
Keyviz 2.0

### ISSUE THREAD

**Issue by Syed1337** [mulaRahul/keyviz#161]
Tested on Windows 11 pro.
1. Not showing`Fn` Key.
2. Other application stop working when Keyviz settings are open
3. Keyviz freezes after sometime.
4. Some keys name are not correctly displayed such as `Tab`
`Enter`, `Backspace`, `pgUp`,`PgDn`, `PrtSc`
5. `+ `separator color is black so it is invisible when background color is enabled and set to black.

**Comment by mulaRahul** [comment]
Can you go through [v2.0.0a2](https://github.com/mulaRahul/keyviz/releases/tag/v2.0.0a2) and get back with feedback on the same?
