### ISSUE TITLE
mouse highlight is off from the cursor when Windows Screen Scale settings set 

### ISSUE THREAD

**Issue by m00nlygreat** [mulaRahul/keyviz#172]
**Describe the bug**
If you set Screen Scale settings on Windows 10, the mouse highlight will be off from the cursor

**Version**: v2.0.0 alpha

**To Reproduce**
1. Go to 'Windows Display Settings'
2. set screen scale to 125% or 150%
3. run keyviz, turn the mouse highlight on.

**Expected behavior**
Mouse highlight will be on the cursor

**Screenshots**

![image](https://github.com/mulaRahul/keyviz/assets/29726529/8cec607f-b8fb-4800-aa6f-36b1a029d2cf)

**Desktop (please complete the following information):**
 - Windows 10

**Additional context**

**Comment by mulaRahul** [comment]
Need to take the scale factor into account when positioning the mouse highlight.

**Comment by m00nlygreat** [comment]
Love this application, thanks!

**Comment by Cierra-Runis** [comment]
This also infact some full screen game, such as osu.

**Comment by POTPER** [comment]
![image](https://github.com/mulaRahul/keyviz/assets/51182932/7d40d06e-78c1-4013-a699-bf7659c91ae5)
I am also like this, if the screen display does not become larger, the display fits the mouse cursor, but I have a 4K screen and can only display at 150%

**Comment by mulaRahul** [comment]
Fixed with #191 by @Ansen-A.
