### ISSUE TITLE
[Bug] Hotkey Filter is not working properly

### ISSUE THREAD

**Issue by ZWolken** [mulaRahul/keyviz#174]
**Describe the bug**
When I turn Hotkey Filter on, the letters, numbers etc still show to screen.

**Version**: v2.0.0 alpha

**To Reproduce**
1. Turn Hotkey Filter on
2. Just type the regular letters etc.
3. Show to screen

**Expected behavior**
As Hotkey Filter turned on, the letters, numbers etc should not be show up.

**Screenshots**
![image](https://github.com/mulaRahul/keyviz/assets/76812845/004e4e47-41c8-46c2-a8bd-e624c2d45ed6)

**Desktop (please complete the following information):**
 - Windows 11

**By the way**
I also think the `space` key is plain, just like what had said in #158.

**Comment by thiagodp** [comment]
Windows 10 also has this bug.

**Comment by mulaRahul** [comment]
Fixed with 83ee5ff8bf7cef54c2fdf7819c4f54eb71d5b0e9
