### ISSUE TITLE
Installation Keyviz V2 on Windows 11

### ISSUE THREAD

**Issue by moufid-elaroui** [mulaRahul/keyviz#175]
The installation of the software does not work on my Win11 pc. I downloaded the version v2.0.0-alpha.

**Comment by mulaRahul** [comment]
Can you share the error message/screenshot?

**Comment by moufid-elaroui** [comment]
I have successfully downloaded the program from the repository, but when I double-click the exe file, no pop-up window appears to continue the installation.

**Comment by mulaRahul** [comment]
Oh, actually the `v2.0.0-alpha` windows release isn't installer instead it's the binary. You can directly run Keyviz by dbl clicking the `.exe`.
