### ISSUE TITLE
The content displayed by pressing the space is empty.

### ISSUE THREAD

**Issue by xing403** [mulaRahul/keyviz#182]
**Describe the bug**
For example, when I press `LeftArrow`, `Left` is displayed. 
But when I press `Space`, it shows an empty space instead of `space`
![1693657889864](https://github.com/mulaRahul/keyviz/assets/74746021/b1408df2-15d7-4437-8d8b-413577e85415)

**Version**: v2.0.0-alpha

**Comment by mulaRahul** [comment]
Duplicate of #158
