### ISSUE TITLE
NULL key pops out and never goes away

### ISSUE THREAD

**Issue by Raynbda** [mulaRahul/keyviz#184]
**Describe the bug**
A key called "Null" pops out of nowhere and stays there until i restart the app 

**Version**: v1.0.6

**To Reproduce**
I'm not sure how to reproduce this problem but i think its linked the replace new key setting

**Screenshots**
![Screenshot 2023-09-09 111450](https://github.com/mulaRahul/keyviz/assets/116586370/3e15d2b2-91e2-4473-8804-8027bb9d6e19)

**Desktop (please complete the following information):**
 - Windows 11 22H2

**Comment by mulaRahul** [comment]
@Raynbda, that same is fixed with v2.0.0-alpha.
