### ISSUE TITLE
重启后的位置并非自定义的

### ISSUE THREAD

**Issue by xing403** [mulaRahul/keyviz#187]
**Describe the bug**
1. 我在设置中，设置显示位置在右下角，边距50px
2. 当我在重新启动时，显示位置在右下角，边距大概100px

* 当我每次登录微信时，总是会显示F22，状态时按下，但并未操作指令。不知道改如何把这个按键给关掉 

**Version**: v2.0.0

**Screenshots**
![image](https://github.com/mulaRahul/keyviz/assets/74746021/15531c04-a922-457e-9306-22ecbbb8bc61)

**Desktop (please complete the following information):**
 - Windows 11

**Comment by Ansen-A** [comment]
F22是因为你启动了桌面端微信，我在测试中发现点开桌面端微信中的公众号文章也会触发虚拟F22，并且一直处于按下去的状态，我的做法是用PowerToys将一个不常用的按键重新映射给F22，这样可以让F22自动弹起来。提供给你参考：

![image](https://github.com/mulaRahul/keyviz/assets/7991430/7b424d2a-04c9-4118-a5f1-b565ce9825a5)

**Comment by mulaRahul** [comment]
The settings gets reset and that's a bug discussed in #196. About the <kbd>F22</kbd>, I think I've heard the same before happening with WeChat.
