### ISSUE TITLE
The key cannot disappear automatically when the headset switches to the previous song or the next song.

### ISSUE THREAD

**Issue by Web0706** [mulaRahul/keyviz#189]
![image](https://github.com/mulaRahul/keyviz/assets/103833016/0fcf0cb0-7a4e-460f-9e30-05811ece38fd)

**Comment by mulaRahul** [comment]
Can you reproduce the same in [v2.0.0a](https://github.com/mulaRahul/keyviz/releases/tag/v2.0.0a)?

**Comment by mulaRahul** [comment]
Closing due to lack of further context.
