### ISSUE TITLE
Set up key filtering

### ISSUE THREAD

**Issue by itzhiyuangao** [mulaRahul/keyviz#195]
**Describe the bug**

**Version**: v2.0.0-alpha

**To Reproduce**

Once the filter hotkey is set, it will still display other keys.

**Expected behavior**

I hope that after setting the filter, only hotkey combinations will be displayed and other key states will not be displayed.

**Screenshots**
<img width="564" alt="image" src="https://github.com/mulaRahul/keyviz/assets/147362832/99ec9574-5acb-4c83-a1a0-f4fdc0f7378b">
<img width="246" alt="image" src="https://github.com/mulaRahul/keyviz/assets/147362832/15ef2143-8535-4563-ab37-0239cca52dc6">
<img width="284" alt="image" src="https://github.com/mulaRahul/keyviz/assets/147362832/cd11bbcd-61a8-4621-bb14-e02719d36ed9">

**Desktop:**
 - Mac os 14.0 (23A344)adsfffgdffoppippppppfasadfsafd

**Additional context**

**Comment by thiagodp** [comment]
The same is happening on Windows 10

**Comment by thiagodp** [comment]
Same as in #174
