### ISSUE TITLE
Key coordinate position setting is invalid

### ISSUE THREAD

**Issue by itzhiyuangao** [mulaRahul/keyviz#196]
**Describe the bug**

**Version**: v2.0.0-alpha

**To Reproduce**

I set the button to be displayed in the lower left corner, but after restarting the button is still wrongly displayed in the lower right corner.

**Expected behavior**

After setting up, restart the computer and hope it takes effect.

**Screenshots**
<img width="1727" alt="image" src="https://github.com/mulaRahul/keyviz/assets/147362832/eb95429d-6a1e-476a-9c7e-c636c19b8ea7">

**Desktop:**
 - Mac os 14.0 (23A344)

**Additional context**

**Comment by MeesterDev** [comment]
I can also reproduce this on Windows 10 Pro N 22H2 (19045.3803).

Best workaround I have found is to change the position setting and reverting it to what you want every time you start.

**Comment by mulaRahul** [comment]
Fixed with [v2.0.0a2](https://github.com/mulaRahul/keyviz/releases/tag/v2.0.0a2)
