### ISSUE TITLE
Customized buttons have adaptive mode

### ISSUE THREAD

**Issue by itzhiyuangao** [mulaRahul/keyviz#197]
Describe the bug

Version: v2.0.0-alpha

To Reproduce

When I customize a button, part of the button text is not fully displayed

Expected behavior

I hope that the custom button has an adaptive mode so that its characters can be fully displayed

Screenshots
<img width="1019" alt="image" src="https://github.com/mulaRahul/keyviz/assets/147362832/1499e642-1f18-4c52-b6a1-2abad35a7308">

Desktop:

Mac os 14.0 (23A344)

**Comment by mulaRahul** [comment]
Fixed with 7fbb37ad0edfd9444221f5845c2f91de8af8f56d
