### ISSUE TITLE
Keyviz_v2.0.0-alpha version upgrade request

### ISSUE THREAD

**Issue by itzhiyuangao** [mulaRahul/keyviz#200]
**Is your feature request related to a problem? Please describe.**
The v2.0.0-alpha Mac os version has many errors. Man, when are you going to update the next version? Thank you for your answer

**Describe the solution you'd like**
Mistake 1: Avoiding other keystrokes does not work
Mistake 2: Settings don’t work after reboot
Error 3: The button display position is always in the lower right corner. After exiting the software after setting, it returns to the lower right corner.
Error 4: The Command button on the right side of the keyboard does not display properly
Mistake 5: Customized shortcut keys often fail after setting them

**Describe alternatives you've considered**
Looking forward to you updating these bugs in the new version

Computer model: Mac book pro 16
System version: Mac os14.0 (23A344)
Software version: keyviz_v2.0.0-alpha

**Comment by mulaRahul** [comment]
Totally agree the current Mac release cannot be considered even a stable release. But, that's the first step into Mac. You should expect the new release soon.

**Comment by mulaRahul** [comment]
Any feedback on [v2.0.0a2](https://github.com/mulaRahul/keyviz/releases/tag/v2.0.0a2)?

**Comment by songxianpeng** [comment]
> Any feedback on [v2.0.0a2](https://github.com/mulaRahul/keyviz/releases/tag/v2.0.0a2)?对 v2.0.0a2 有任何反馈吗？

<img width="490" alt="image" src="https://github.com/mulaRahul/keyviz/assets/9303424/7c9b391d-80b8-4fc4-aa62-e4e725051cca">

all keys not work when hotkeys filter enabled,but modifier keys always not work  on macos 14.4.1 (23E224)

**Comment by mulaRahul** [comment]
Indeed the modifiers aren't getting reported. I've updated the release, can you check again?

**Comment by songxianpeng** [comment]
> Indeed the modifiers aren't getting reported. I've updated the release, can you check again?

works good without hotkey filter :D.
