### ISSUE TITLE
Keyviz v1.0.6 “Replace new key”=Append, display all keys

### ISSUE THREAD

**Issue by jasperc2012** [mulaRahul/keyviz#201]
keyviz is an awesome software.

It works well to dispaly the keys, but it seems that keys will be all displayed when different keys are pressed. When same key is pressed, it "erases" the other keys.

For example, I pressed "test", it looks like only "t" is displayed. In some cases, it will be better if all "t e s t" can be displayed.

**Comment by piterq** [comment]
+1 for this. It could be dependent on configurable option (in case some users like current behavior).

**Comment by mulaRahul** [comment]
Appending same keys can make it harder for the code to add/remove keys. As keyviz doesn't just add keypress events on a stack one after another, it add/removes keys on key up/down, hotkey filters, history, etc.

Though it is possible by assigning each key event a unique id and a switch to see if a key is already pressed/removed/duplicate but that means adding another layer of complexity from the top. It's a tradeoff I took to support the other features.

**Comment by jasperc2012** [comment]
Yes sir.
