### ISSUE TITLE
我启动后鼠标指针跟圈圈偏倚5CM

### ISSUE THREAD

**Issue by ruru023** [mulaRahul/keyviz#202]
**Describe the bug**
打开软件，开启鼠标效果，指针和圈圈不在一起
指针永远在圈圈左上方

**Version**:  V2.0.0a

**To Reproduce**
应该不是每个人都这样，不然早就报了

**Expected behavior**
指针应该在圈圈内部吧，

**Screenshots**
![image](https://github.com/mulaRahul/keyviz/assets/4388095/16e76d63-afb2-4b80-a958-18a40c0a3511)

**Desktop (please complete the following information):**
 - Windows 10

**Additional context**

**Comment by DoiiarX** [comment]
我也遇到了同样的情况。经过我排查，应该是没有矫正屏幕分辨率。左上角没问题，越右下角，偏离越大。

**Comment by Alwin233** [comment]
win11有同样的问题

**Comment by mulaRahul** [comment]
Duplicate of #213.
