### ISSUE TITLE
Part of the preview window is transparent

### ISSUE THREAD

**Issue by charmarkk** [mulaRahul/keyviz#211]
**Describe the bug**

**Version**: v1.0.6

**To Reproduce**
1. Install on machine
2. Open application
3. Observe part of the preview window is transparent (I didn't do anything else other than install the app)

**Expected behavior**
The window should not be transparent, unless intended?

**Screenshots**
![image](https://github.com/mulaRahul/keyviz/assets/22264269/4eeca340-dfb3-4924-9aad-76cddfa913d8)

**Desktop (please complete the following information):**
 - Windows 10

**Additional context**
I'm not sure what other info would be helpful, but happy to provide anything I can.

**Comment by markjoshwel** [comment]
pretty sure this is intended, so you can see how it looks when displayed on the desktop/an application

**Comment by mulaRahul** [comment]
Hey @charmarkk, the transparent design is discontinued from the v2 so you don't need to worry about the same. Also, as mark pointed out, it was intentional 😅
