### ISSUE TITLE
Support Multiple Screen

### ISSUE THREAD

**Issue by pojokcodeid** [mulaRahul/keyviz#212]
Hai,

I hope this email finds you well.

I am writing to request support for multiple screen recording. I currently use multiple desktops to record my screen, but I am only able to record shortcuts on the primary screen. I would appreciate it if you could add support for recording shortcuts on all active screens.

Thank you for your time and consideration.

Regards

**Comment by junjie-lean** [comment]
是的，我也有同样的需求。 并且在其他程序全屏的时候，比如Chrome、vsCode，该如何启用本程序呢?

**Comment by thiagodp** [comment]
Duplicated. Please see #96
