### ISSUE TITLE
Mouse highlight position incorrect on Windows

### ISSUE THREAD

**Issue by manaliveadam** [mulaRahul/keyviz#213]
**Describe the bug**
If the mouse is in the upper left corner, the highlight is in the correct position.  However, as you move it away from the corner, the highlight moves twice as far as the mouse, so by the time the cursor is in the middle of the screen the highlight is in the bottom right corner.  My display is set to 200% resolution so that could be the issue?  But setting it to 100% doesn't change anything.

**Version**: v2.0.0

**To Reproduce**
1. Install Keyviz on Windows
2. Enable "Visualize Clicks"
3. It should happen automatically

**Expected behavior**
I expect the highlight to follow the mouse exactly

**Screenshots**
![image](https://github.com/mulaRahul/keyviz/assets/63170980/dfab4463-6a22-4986-8bc0-02f061506ae7)
Screenshot of me clicking on the word "position" but the highlight in the bottom right.

**Desktop (please complete the following information):**
 - Windows 11

**Additional context**
Love Keyviz!

**Comment by fexa6** [comment]
same problem，im using a 2k res screen by the way，dont know if this information helps。

**Comment by m00nlygreat** [comment]
Guys, this problem has been resolved few months ago. You need to download the source code and build the application on your own.

**Comment by aaazv** [comment]
> Guys, this problem has been resolved few months ago. You need to download the source code and build the application on your own.

Not everyone is an expert on building softwares. Can you share your built software that has fixed this problem?

**Comment by mulaRahul** [comment]
The same shouldn't be an issue in the next release.
