### ISSUE TITLE
Click animation is not visible at screen ends in keyviz

### ISSUE THREAD

**Issue by frank82vt** [mulaRahul/keyviz#214]
**Bug Description**
In the video you can see that the click animation disappears when the mouse pointer approaches the ends of the screen such as right left up down and extreme vertices.This problems happens in keyviz version 2.0 

**Version**: v2.0

**To Reproduce**
1. Go to 'keyviz 2.0, settings, mouse, activate Visualize clics '
2. See error

**Expected behavior**
The click animation has its center at the point pointed by the mouse pointer. Additionally, also add an option to decenter the animation of the mouse pointer click but adjust the position of said animation so that it is always visible within the screen

**video**
See video attached 

**Desktop**
 - Windows 11 Pro

https://github.com/mulaRahul/keyviz/assets/84551251/a79dd5a3-1568-4035-86d4-378b3316f421

**Comment by aaazv** [comment]
Dear @mulaRahul would you please fix the highlight being far from the cursor or tell us how to fix it with higher scale in a video or step by step text instruction? Thank you.

**Comment by mulaRahul** [comment]
The same is happening because right now keyviz doesn't take device-pixel-ratio into consideration. Same is discussed in #213.
