### ISSUE TITLE
I am unable to open it on macOS M1 Big Sur version 11.2.3. 

### ISSUE THREAD

**Issue by slince-zero** [mulaRahul/keyviz#215]
**Describe the bug**
The software crashes when I click on it

**Version**: v2.0.0

**Comment by AutoSponge** [comment]
I had to use `sudo xattr -dr com.apple.quarantine <path to file>/keyviz.app`

**Comment by mulaRahul** [comment]
Hey @slince-zero, do you get any specific errors/logs?

**Comment by mulaRahul** [comment]
Will be further tracked in #171.
