### ISSUE TITLE
NO Save settings

### ISSUE THREAD

**Issue by deodatopr** [mulaRahul/keyviz#220]
dd**Describe the bug**
If I make any changes inside of the settings the app was saved, but if I close it and re open it, the settings remains as the default, but if I change just one option what I did before, everything start again work as all the settings are in the setting panels.

**Version**: v2.0.0-Alpha
Using Windows 11

Recorded a Movie with the issueÑ
https://github.com/mulaRahul/keyviz/assets/16979750/6d3f7026-cb2e-4e0c-8464-aaaef50ff2b0

**Comment by mulaRahul** [comment]
Fixed with [v2.0.0a2](https://github.com/mulaRahul/keyviz/releases/tag/v2.0.0a2)
