### ISSUE TITLE
libappindicator3 shared library lack on Arch Linux

### ISSUE THREAD

**Issue by xbelanch** [mulaRahul/keyviz#221]
**Describe the bug**
./keyviz: error while loading shared libraries: libappindicator3.so.1: cannot open shared object file: No such file or directory

**Version**: v2.0.0 alpha

**To Reproduce**
1. Download binary for linux_x64 from Releases site 
2. Unzip
3. Execute
4. See error: ./keyviz: error while loading shared libraries: libappindicator3.so.1: cannot open shared object file: No such file or directory

**Desktop (please complete the following information):**
 - Arch Linux x86_64 Kernel: 6.6.10-arch1-1 NVIDIA GeForce RTX 2060 Rev. A

**Comment by mulaRahul** [comment]
On linux, the `libappindicator3` is required. Run the following command/s -

```
sudo apt-get install libayatana-appindicator3-dev
```
Or
```
sudo apt-get install appindicator3-0.1 libappindicator3-dev
```

**Comment by RealYukiSan** [comment]
for some reason I need to create a symbolic link manually:

```
sudo ln -svf /usr/lib/libayatana-appindicator3.so /usr/local/lib/libappindicator3.so.1
```
