### ISSUE TITLE
Mouse visualization in the wrong location when using screen scaling

### ISSUE THREAD

**Issue by MichielVT** [mulaRahul/keyviz#228]
On a windows 11 system, when scaling is enabled for a certain screen, e.g. set to 125%, the mouse indicator will be shown in a different location than the actual mouse pointer.

**Comment by willie91** [comment]
So do I

**Comment by mulaRahul** [comment]
Fixed with [v2.0.0a2](https://github.com/mulaRahul/keyviz/releases/tag/v2.0.0a2)
