### ISSUE TITLE
Multi-Monitor Support

### ISSUE THREAD

**Issue by GLITCHRS** [mulaRahul/keyviz#229]
**Is your feature request related to a problem? Please describe.**
I tried to install the latest version of the app, it's good, but the problem is I cannot choose on which monitor I'd like to display the keycaps, also, when I move the window of the app to the other window it disappears for some reason.

**Describe the solution you'd like**
Please implement multi-monitor support & fix the bug where moving the window to another monitor causes the window to disappear.

**Comment by thiagodp** [comment]
Duplicated. Please see #96

**Comment by thiagodp** [comment]
Duplicated. Please see #96

**Comment by thiagodp** [comment]
Duplicated. Please see #96
