### ISSUE TITLE
Unable to close mouse event in taskbar

### ISSUE THREAD

**Issue by Alanclaude** [mulaRahul/keyviz#232]
**Describe the bug**
Unable to close mouse event in taskbar
无法在任务栏关闭mouse event

**Version**: v2.0.0-alpha

**To Reproduce**
1. Disable the hotkey filter
2. Open show mouse events
3. Close keiviz in the taskbar ![QQ截图20240128033547](https://github.com/mulaRahul/keyviz/assets/77158950/9067b45d-a20d-4720-99e3-2bbbfe44aa71)
5. Now you can still see the pattern with a mouse click

**Expected behavior**
Mouse detection is turned off along with key detection
鼠标检测和键检测一起被关闭

**Desktop (please complete the following information):**
 - Windows 11

**Additional context**

**Comment by mulaRahul** [comment]
Fixed with [v2.0.0a2](https://github.com/mulaRahul/keyviz/releases/tag/v2.0.0a2)
