### ISSUE TITLE
Cursor position offset

### ISSUE THREAD

**Issue by 1158191255** [mulaRahul/keyviz#234]
**Describe the bug**
The cursor position is correct only at 1440*900 resolution. At 1600*900 or 1920*1080 resolutions, it is correct when the cursor is in the upper left corner of the screen, and the display is shifted to the lower right when the cursor is in other positions on the screen.

**Version**: v2.0.0

**Screenshots**
![2024-02-01_210219](https://github.com/mulaRahul/keyviz/assets/18094064/58220992-1224-4dad-8269-317d65d50e41)

**Desktop (please complete the following information):**
 - Windows 10 22H2

**Comment by mulaRahul** [comment]
Fixed with [v2.0.0a2](https://github.com/mulaRahul/keyviz/releases/tag/v2.0.0a2)
