### ISSUE TITLE
Add color picker to key color, modifier color and border color

### ISSUE THREAD

**Issue by Snailedlt** [mulaRahul/keyviz#237]
**Is your feature request related to a problem? Please describe.**
I wish I could change the colors to anything I like. Especially changing the transparency level

**Describe the solution you'd like**
I'd like to be able to choose any color using a color picker. The color picker should let me choose a color either by selecting the color with my mouse on a color spectrum, or by inputting an ARGB or RGB hex value for example `#55014324` or `#014324`.

The color picker should have two input fields for `Key Color` and `Modifier Color`, one for the text, and one for the keycap color. For Border color it should just be a single input field.

**Describe alternatives you've considered**

**Additional context**

These are the options I want a color picker on:
![image](https://github.com/mulaRahul/keyviz/assets/43886029/f5c10951-5ad2-443d-8f32-db91c846d991)

An example [color picker from google](https://www.google.com/search?q=color+picker):
![image](https://github.com/mulaRahul/keyviz/assets/43886029/704f53e5-efd0-436d-92a2-2259b9168b95)

**Comment by mulaRahul** [comment]
The same is already in works 👉 [v2.0.0a2](https://github.com/mulaRahul/keyviz/releases/tag/v2.0.0a2)
