### ISSUE TITLE
The mouse position is inconsistent with the aperture position

### ISSUE THREAD

**Issue by RuixiangS** [mulaRahul/keyviz#239]
**Describe the bug**
The mouse position is inconsistent with the aperture position.

**Version**: v2.0.0a

**To Reproduce**
1. Go to Mose setting
2. Click on Visualize Clicks
3. Click somewhere

**Expected behavior**
The mouse position overlaps the aperture position.

**Screenshots**
![1708520888481](https://github.com/mulaRahul/keyviz/assets/29591339/b405489a-a828-4111-a2ae-1b389d144139).

**Desktop (please complete the following information):**
 - Windows 10

**Comment by candideu** [comment]
Same issue on my end with Windows 10. Not sure if it's because of my 2nd monitor...
