### ISSUE TITLE
Key visualizer's position reset to default if you close the application

### ISSUE THREAD

**Issue by blueeln** [mulaRahul/keyviz#245]
**Describe the bug**
If you change the key visualizer margin in the settings it seems that it resets to default if you close the application via the system tray.

**Version**: 2.0.0-alpha

**To Reproduce**
1. Launch the application
2. Open the control panel in the system tray.
3. Change the margin settings
4. Close the application via the system tray.
5. Re-open the application, press a few keys and observe.

**Expected behavior**
Expecting the margin settings to save between sessions.

**Screenshots**
https://youtu.be/vmW5F9TkDhw

**Desktop (please complete the following information):**
 - Windows 10

**Comment by mulaRahul** [comment]
Fixed with [v2.0.0a2](https://github.com/mulaRahul/keyviz/releases/tag/v2.0.0a2)
