### ISSUE TITLE
Keyviz 2.0a Trial Questions

### ISSUE THREAD

**Issue by wdd500** [mulaRahul/keyviz#246]
Keyviz试用问题：
1、turn off：功能无用，设定turn off，还是显示。
![image](https://github.com/mulaRahul/keyviz/assets/58577706/aed1ec24-2ebd-4dc3-b56f-e36ae6449e3e)
2、Alignment项：设定为除右下角的位置，均不会保存，在关闭应用后，重新打开后总是在右下角出现。
![image](https://github.com/mulaRahul/keyviz/assets/58577706/6371630e-c658-418c-868f-0e5cea7cc395)
3、在使用一定时间后，鼠标拖动键会一真显示在第1个位置，是不是鼠标键盘操作同时也操作鼠标，鼠标不拖点只是单击也会触发，因为单击时鼠标不可能一动不动，会有轻微的移动，是不是可以把拖动阈值调整一下，减少其多操作下的不当显示。
![image](https://github.com/mulaRahul/keyviz/assets/58577706/956bfdd5-a6ba-434e-844b-fd90e5c1e91e)
4、Visualize Clicks：鼠标这个触点那个红圈没有在光标位置，而是在光标右下方比较远的地方，我个人理解应该是跟随光标的，这不知道是不是设计初衷。
![image](https://github.com/mulaRahul/keyviz/assets/58577706/2340e55b-e031-4e91-b30c-0cc9fc02324e)
这几个问题要是修复了，基本上在平时使用上是没有什么问题的。

Keyviz Trial Questions:

1. Turn off: The function is useless. Set turn off or display.

2. Alignment item: Set to a position other than the bottom right corner, which will not be saved. After closing the application and reopening it, it will always appear in the bottom right corner.

3. After using it for a certain period of time, the mouse drag button will appear in the first position. Is it possible that the mouse and keyboard operations also operate the mouse, and clicking without dragging the mouse will trigger it? Because when clicking, the mouse cannot remain stationary and may move slightly, can the drag threshold be adjusted to reduce improper display under multiple operations.

4. Visualize Clicks: The red circle on the mouse touch point is not located at the cursor position, but rather far below the cursor to the right. Personally, I understand that it should follow the cursor, but I don't know if this is the original design intention.

If these issues are fixed, there are basically no problems in daily use.

**Comment by mulaRahul** [comment]
Can you check if the problems exist with [v2.0.0a2](https://github.com/mulaRahul/keyviz/releases/tag/v2.0.0a2)?

**Comment by mulaRahul** [comment]
Closing due to lack of context.
