### ISSUE TITLE
Link to project on become a sponsor page 404s 

### ISSUE THREAD

**Issue by funvill** [mulaRahul/keyviz#248]
Steps to reproduce 
1. Goto this page https://github.com/sponsors/mulaRahul
2. Click "Keyviz" in the intro description. This leads to this url https://mularahul.github.io/keyviz.html that produces a Error 404

![image](https://github.com/mulaRahul/keyviz/assets/314120/05c211ed-ec5c-453e-8ef3-3fc09b871ff1)

Also missing image 

![image](https://github.com/mulaRahul/keyviz/assets/314120/944383f6-9ced-46e3-b9dd-fcb141e5cbfd)

**Comment by mulaRahul** [comment]
Thanks for pointing that out!
