### ISSUE TITLE
There is always the F22 button on the screen and it does not disappear

### ISSUE THREAD

**Issue by iooiAsrr** [mulaRahul/keyviz#251]
![image](https://github.com/mulaRahul/keyviz/assets/145520104/80dc920b-404a-4d9e-8c24-814747504139)

**Comment by iooiAsrr** [comment]
微信的问题

**Comment by QAbot-zh** [comment]
> 微信的问题

怎么说，我也遇到了，可以怎么消除吗

**Comment by muheilian** [comment]
if this happened when you open wechat,it's normol. the "F22"will be always pushsd by wechat.
you can download a APP"quiker",there's way to solve. go have a try,bro!
