### ISSUE TITLE
Issues about mouse events, wrong focus postion due to dpi and "drag" wont disappear

### ISSUE THREAD

**Issue by void285** [mulaRahul/keyviz#252]
**Describe the bug**
1、mouse focus/hightlight at wrong position, maybe due to my desktop dpi set to 125%
2、"drag" shown wont disapper sometimgs, I must trigger drag again to disapper it, without 100% success rate

**Version**: v2.0.0a

**To Reproduce**
1. set desktop to 125%
2. enable mouse events capture
3. click, drag

**Expected behavior**

**Screenshots**
I cant capture a screeshot with only drag shown, so there is also a click include by the screenshot operation
![image](https://github.com/mulaRahul/keyviz/assets/612912/457f52b9-59f6-4a7b-ab4d-b55f7999024a)

I set the mouse focus background to black, to see it clear.
![image](https://github.com/mulaRahul/keyviz/assets/612912/245a0a85-0c5a-4afb-bed1-74cd1f0d4ff5)

**Desktop (please complete the following information):**
 - Windows 10

**Additional context**
I found some new issues, some maybe related to this issue, some maybe not.
1. The "shift" button may stay on screen and dont disappear, just like "drag", so I met with three occurences: drag, shift, shift+drag;
2. After press shift+f10, mouse events still showup, not sure if this is by design;
3. I need to capture the Esc keypress events, with hotkey filter on, it's filtered out, without hotkey filter, many unneeded events captured, it will be great if there is shortcut switch to enable/disable the hotkey filter
4. Some setup wont work immediately, enable/disable the hotkey filter for example, restart the app will make it take effect
5. After disable hotkey filter, mouse events wont be captured, not sure if this is by design;

**Comment by Jin1c-3** [comment]
The bugs have been fixed in the latest code `v2.0.0a2`, try building it yourself.
