### ISSUE TITLE
can not run

### ISSUE THREAD

**Issue by qyouqme** [mulaRahul/keyviz#257]
**Describe the bug**

After double click the shortcut, nothing happen, no window, no tray icon.

**Version**: v2.0.0a2

**To Reproduce**
double click the shortcut

**Expected behavior**
open a window
**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11

**Additional context**
v2.0.0a1 work fine

**Comment by mark05e** [comment]
Same on windows 10.

**Comment by mulaRahul** [comment]
I've updated the windows release, can you check if the issue is fixed?

**Comment by mark05e** [comment]
App runs on Windows 10 now. Thank you!
