### ISSUE TITLE
Report two bugs

### ISSUE THREAD

**Issue by Uiudex** [mulaRahul/keyviz#258]
**Description:**

The first bug：The software settings cannot be saved. After the software is restarted, the settings return to the initial settings.

The second bug：Mouse-related functions cannot be used. After turning on mouse-related functions, only a quarter arc is displayed in the upper left corner of the screen.

**Version**: [v2.0.0-alpha2](https://github.com/mulaRahul/keyviz/releases/tag/v2.0.0a2)

**To Reproduce**

**I have enabled relevant functions**
<img width="457" alt="PixPin_2024-04-24_22-47-01" src="https://github.com/mulaRahul/keyviz/assets/167489322/8291cbcc-b7bc-4bd8-a027-4c9bb9fd6c3f">
**After turning on this function, an aperture will appear in the upper left corner of the screen：”**
<img width="64" alt="PixPin_2024-04-24_22-47-38" src="https://github.com/mulaRahul/keyviz/assets/167489322/dd130918-7bb7-40c7-8901-448783918f86">

**Expected behavior**
Fix mouse related functions, the software saves my settings

**Desktop (please complete the following information):**
 - Windows 11

**Greetings to the author：**
Hello, author, I am a teacher. Because of the COVID-19 epidemic, I was forced to teach my students online. For a better demonstration, I got to know this software and recommended it to other teachers around me and got it. Their praise is unanimous and thank you for the support you give me when I teach. It is greatly appreciated.

**Comment by mark05e** [comment]
I have the same issue as well with regards to settings getting reset after application restart.

**Comment by mulaRahul** [comment]
I've fixed the issue, and updated the [release](https://github.com/mulaRahul/keyviz/releases/tag/v2.0.0a2). Can you confirm if the issue is resolved?

**Comment by Uiudex** [comment]
> 我已经解决了这个问题，并更新了[版本](https://github.com/mulaRahul/keyviz/releases/tag/v2.0.0a2)。您能否确认问题是否已解决？
Both bugs are fixed

**Comment by mark05e** [comment]
Confirm issues resolved - settings and mouse actions.
