### ISSUE TITLE
Mouse Actions do not work

### ISSUE THREAD

**Issue by mark05e** [mulaRahul/keyviz#259]
**Describe the bug**
Mouse related settings are enabled inside the application. But it does display any information on screen.

**Version**: v2.0.0-alpha2

**To Reproduce**
- Launch app. Enable Visualize Clicks.

**Expected behavior**
- Mouse to show highlights and related events.

**Screenshots**
![image](https://github.com/mulaRahul/keyviz/assets/1783193/b6d161a2-a7f8-41d2-8d2f-6724088199c9)

**Desktop (please complete the following information):**
 - Windows 10 22H2

**Additional context**
Could be similar to https://github.com/mulaRahul/keyviz/issues/258

**Comment by mulaRahul** [comment]
If you're using multiple monitors, share screenshots of the **Settings > Appearance** page and your screen.

**Comment by mark05e** [comment]
Yes I was trying it out on multi-monitor setup at the time. I just tried single monitor setup as well - seems to be the same issue.

![image](https://github.com/mulaRahul/keyviz/assets/1783193/e53fb21d-367e-4176-9e5e-34b040e9f4f1)

Will upload multi monitor screenshot soon.

**Comment by mark05e** [comment]
Here is the other screenshot. I apologize if I misunderstood the request.

![image](https://github.com/mulaRahul/keyviz/assets/1783193/cf722006-9651-401b-a7c1-5a9c8745e2fd)

Screen one is disabled.
