### ISSUE TITLE
Portable Release

### ISSUE THREAD

**Issue by Riajyuu** [mulaRahul/keyviz#27]
I expect using keyviz without installation and keyviz writing all config files within the same folder

**Comment by mulaRahul** [comment]
That's something I've considered performing but unfortunately the build has a lot of files and folders along with it (flutter-windows related), so making a portable of the same isn't possible. 

I've skimmed through some videos online and found that you can easily create a portable version of this (or any) app using special tools like [cameyo](https://cameyo.com/).

**Comment by damywise** [comment]
https://enigmaprotector.com/en/aboutvb.html
