### ISSUE TITLE
关于鼠标点击的一点建议 A word of advice about mouse clicks

### ISSUE THREAD

**Issue by BlackRosePetals** [mulaRahul/keyviz#277]
建议增加鼠标点击的显示按钮,包括点击的案件图标和点击次数.
It is recommended to increase the number of mouse clicks on the display button, including the case icon and the number of clicks.

例如下图所示:
For example, the following figure shows:

![Carnac汉化版_COfIQmCEdl](https://github.com/mulaRahul/keyviz/assets/53809038/d7ded303-4495-4955-b563-a7b589dd25c3)
![Carnac汉化版_yFyMPTOzyF](https://github.com/mulaRahul/keyviz/assets/53809038/16bc9376-852c-41ed-916f-ae2661b0cf9a)
![Carnac汉化版_ZnbFVdr6to](https://github.com/mulaRahul/keyviz/assets/53809038/f81b2115-cb82-4b9c-9754-45bc8f27fbd6)

**Comment by mulaRahul** [comment]
Closing in favor of #272.
