### ISSUE TITLE
Keys not disappearing after being pressed (Ctrl + Shift + Esc, Ctrl + Alt + Delete)

### ISSUE THREAD

**Issue by Nightcore-8bit** [mulaRahul/keyviz#283]
I usually use the shortcut Ctrl + Shift + Esc in order to open Task Manager on Windows. And so, it is being properly visualized when I press them, however, they do not disappear afterwards. In order to make them disappear, I have to press each key individually.

**Version**: v2.0.0-alpha2

**To Reproduce**
Either press Ctrl + Shift + Esc, or Ctrl + Alt + Delete.

**Screenshots**
https://github.com/mulaRahul/keyviz/assets/68033226/7d1f4ca8-1575-4806-b3db-78fe9441cecd

**Desktop:**
 - Windows 10

**Comment by mulaRahul** [comment]
I can reproduce the same. The `KeyDown` events isn't followed by `KeyUp` events causing the visualization to stick.

**Comment by mulaRahul** [comment]
Will be further tracked in #23.

**Comment by senzyo** [comment]
**Version**: v2.1.1-beta
**Desktop**: Windows 10

This problem has occurred again. The current manifestation is:
After pressing `Ctrl`+`Alt`+`Delte`, the `Ctrl` and `Alt` keys do not automatically disappear, and the `Delte` key sometimes automatically disappears.
