### ISSUE TITLE
Disabling keycap background cause mechanical keycap lengthening

### ISSUE THREAD

**Issue by frank82vt** [mulaRahul/keyviz#286]
**Bug description**
In the video you can see that disabling keycap background cause mechanical keycap lengthening. This bug only happen with mechanical keycap not with the other keycap types 

**Version**: v2.0.0a2

**To Reproduce**
1. Go to keyviz, settings, keycap, 
2. preset section, select mechanical keycap
3. background section, disable, the bug appear
4. repet the same steps changing the keycap types in step 2, preset section, the bug does not appear

**Expected behavior**
when keycap background is disabled, mechanical keycap should not lenghten

**Video**
-see video attached

**Desktop**
 - Windows 11 pro
  
https://github.com/mulaRahul/keyviz/assets/84551251/0f5c49be-45fc-4a87-a1fd-45a2bcb99260

**Comment by mulaRahul** [comment]
That's a nasty bug. Will get it fixed in the next release.
