### ISSUE TITLE
Can control be modified to ctrl? This will be more intuitive

### ISSUE THREAD

**Issue by XIANYU3** [mulaRahul/keyviz#288]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by XIANYU3** [comment]
Can control be modified to ctrl? This will be more intuitive

**Comment by mulaRahul** [comment]
What version are you using?

**Comment by mulaRahul** [comment]
As the same can be done in **v2.0.0a2**, closing the same.
