### ISSUE TITLE
The center alignment icons in the `Keycap -> Layout` settings seem to be mixed up.

### ISSUE THREAD

**Issue by agung-adhinata** [mulaRahul/keyviz#289]
**Describe the bug**
Maybe this is minor bug, yet this little thing doesn't escape my mind when I already notice it.  The align center icon on horizontal alignment is not the correct one, that icon should be swapped with center icon on vertical alignment which is also incorrect. 

This thing sometimes makes me confused when the layout settings is work unexpectedly. I though the app was bugged at first.

**Version**: v2.0.0-alpha2

**To Reproduce**
1. Open `Settings`
2. Select `Keycap`, and click `Layout` accordion to show the layout settings
3. You will see that the center alignment icon between vertical and horizontal alignment section seems to be placed in the wrong place

**Expected behavior**
the align center icon between vertical alignment and horizontal alignment should be placed in right spot

**Screenshots**
this is the current icon at Layout settings

<img width="457" alt="image" src="https://github.com/mulaRahul/keyviz/assets/66739515/1fad8374-0bb3-43a7-8016-637624cb4434">

and this is the alignment icon at other application (Figma). As you can see, the center icon is match the rest of the icons.
<img width="191" alt="image" src="https://github.com/mulaRahul/keyviz/assets/66739515/a590add9-d963-4feb-9723-e6700c3c2f7a">

**Desktop (please complete the following information):**
 - Windows 11

**Additional context**

**Comment by mulaRahul** [comment]
Nice call, will fix in the next release!
