### ISSUE TITLE
The homepage says "contorl"

### ISSUE THREAD

**Issue by Explosion-Scratch** [mulaRahul/keyviz#29]
![image](https://user-images.githubusercontent.com/61319150/185706522-d3fde502-db81-482d-91dc-a70ba47f5a75.png)
![image](https://user-images.githubusercontent.com/61319150/185706561-a9602d1a-8054-4f35-9d8b-0c5562af4925.png)
![image](https://user-images.githubusercontent.com/61319150/185706598-ec8da4da-5c7f-43f4-82bf-e7387af035e2.png)
![image](https://user-images.githubusercontent.com/61319150/185706384-02f43fea-b8ea-4a0f-9aac-41386a24fde5.png)
![image](https://user-images.githubusercontent.com/61319150/185706406-b1d6b424-2200-4f75-8039-1caef2d13b35.png)
![image](https://user-images.githubusercontent.com/61319150/185706430-4209bc8e-410f-4b6a-a924-10beeef52847.png)

**Comment by Explosion-Scratch** [comment]
Honestly, these typos are getting out of **contorl**

![](https://media4.giphy.com/media/U6WxwPyG43QGs/giphy.gif)

**Comment by Explosion-Scratch** [comment]
Lol it says it in like 5 places, also on the website

**Comment by mulaRahul** [comment]
Okay ...didn't see that coming😅. Good job, pointing those typos out!
