### ISSUE TITLE
auto-starting

### ISSUE THREAD

**Issue by the-jsc** [mulaRahul/keyviz#300]
Is it possible to have the function of auto-starting when the device boots up?

**Comment by jlygithub** [comment]
Yes, it's simple. Here is an example for a Windows user:

1. Locate the path of your "keyviz.exe"
2. Add the path of "keyviz.exe" to the registry

If you want to use PowerShell, please save the below script as `*.ps1`, and run it. Don't forget to assign the absolute path of keyviz.exe to $Value.
```PowerShell
$RegistryPath = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run'
$Name         = 'Keyviz'
$Value        = '"<path of keyviz.exe>"'
New-ItemProperty -Path $RegistryPath -Name $Name -Value $Value -PropertyType String -Force
```

**Comment by the-jsc** [comment]
@jlygithub Thank you!
