### ISSUE TITLE
No "Replace new key" option in "keyviz-v2.0.0a2-windows" version

### ISSUE THREAD

**Issue by CaptainMusX** [mulaRahul/keyviz#301]
Hello, I couldn't find the "Replace new key" option in the "keyviz-v2.0.0a2-windows" version that was available in version "v1.0.6". Has this option been removed? I found it quite useful. It would be even better if we could set the number of displayed historical operations, for example, keeping 3 operations. When the user presses a new key, the third-to-last record would disappear and a new record of the current operation would be added. It would also be great to have the ability to set the duration for displaying the pressed keys, for example, disappearing after 3 seconds.
![2024-09-12_10-59-44](https://github.com/user-attachments/assets/780a7c61-b1fa-4c13-8865-9138d9379999)

**Comment by mulaRahul** [comment]
In favor of the **Replace new key** option, the **Show History** is added. It can be found inside the **General** settings. To get the same behavior, set it to **None**.

<img width="475" alt="image" src="https://github.com/user-attachments/assets/79509787-e93a-4b8f-8458-0fea1758b56b">

> ...if we could set the number of displayed historical operations...

Will be further tracked in #298.

> It would also be great to have the ability to set the duration for displaying the pressed keys, for example, disappearing after 3 seconds.

Use the **Duration** option, inside the appearance settings.

<img width="464" alt="image" src="https://github.com/user-attachments/assets/c748e866-fb8a-414c-8aab-1315cacd956c">

**Comment by DBaob** [comment]
Thanks.
