### ISSUE TITLE
可以考虑做个全键盘+鼠标的实时显示功能

### ISSUE THREAD

**Issue by QQ804218** [mulaRahul/keyviz#314]
![image](https://github.com/user-attachments/assets/8c58df93-6d27-45cd-8cc8-4cb969dbd94d)
如图,在键盘(图中是游戏键盘,最好有全按键键盘)+鼠标上实时显示操作...这样的话,更直观更形象...
键盘与鼠标背景最好是全透明的,这样不影响全局还能更好的显示出来效果...
------------------------------------------------------------------------------------------------------
As shown in the picture, real-time display of operations on the keyboard (game keyboard in the picture, preferably a full key keyboard)+mouse In this way, it is more intuitive and vivid
It is best for the keyboard and mouse background to be fully transparent, so as not to affect the overall display and achieve better display effects

**Comment by cyy-2024** [comment]
It may not be possible that all keys need to be demonstrated. The display of all keys may obscure the view...

**Comment by QQ804218** [comment]
这个功能对新人所做的视频会很有用的...

**Comment by mulaRahul** [comment]
I totally get it where you're coming from but this kind of _fixed-display_ is more targeted toward gamers. Keyviz is meant to be used in every kind of scenario but for gaming, will need a different solution altogether. Still, thanks for your suggestion, let's see what others have to say about the same.
