### ISSUE TITLE
It is not shown when VSCode active.

### ISSUE THREAD

**Issue by leo95123** [mulaRahul/keyviz#33]
It is not shown when VSCode active.

**Comment by mulaRahul** [comment]
I can use it just fine with VS Code. 

https://user-images.githubusercontent.com/96373135/185866608-0ab44608-ad59-4aa6-8811-a91b58ec0024.mp4

Are you sure that's really the problem? Can you share videos/images of the issue with some more info?

**Comment by leo95123** [comment]
I changed another app,it is also not shown. Maybe my PC have some problems, sry.
And, this app is so cool, I like it.

**Comment by mulaRahul** [comment]
Are you using the portable version?

**Comment by leo95123** [comment]
No, I installed it.

**Comment by mulaRahul** [comment]
Is there any error message (like _.dll missing_) when you run the application or anything else? Also, can you share your system specs?

**Comment by leo95123** [comment]
No error message.
![image](https://user-images.githubusercontent.com/28439527/185871277-a5cb4e82-51c5-4acf-9c27-b254da1b381c.png)

**Comment by mulaRahul** [comment]
I've run the application on **Windows 10 Home Edition 20H2** (Virtual Box) and it worked fine. Don't know what's causing the problem on your end 🤔?

![window10-20h2-snip](https://user-images.githubusercontent.com/96373135/182152487-493d84c3-756f-42d8-a7b3-9b8bb5ec7230.png)

Maybe you can try upgrading to Windows 10 **21H2** edition (which may fix some internal issues) and running the application after re-installing it.

**Comment by leo95123** [comment]
OK, thx.
