### ISSUE TITLE
Not showing when using blender 

### ISSUE THREAD

**Issue by atticus-lv** [mulaRahul/keyviz#37]
**Describe the bug**
When using blender 3.2 on win11, it will not show the key

**Version**: v1.0.2

**To Reproduce**
download blender on steam
open it 
press some keys

**Expected behavior**
keys should show when using blender's shortcut

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11

**Additional context**

**Comment by atticus-lv** [comment]
seems that I need to restart blender to show the keys.
Any solution to make it init when already open a blender?(just like what have been done with web broswer)

**Comment by mulaRahul** [comment]
Theoretically, it should work with any software as it doesn't rely on other software in any way. The application starts listening to keyboard inputs and visualizes them on top of other applications https://github.com/mulaRahul/keyviz/issues/35#issuecomment-1223622700.

Now other software can hide the keystroke visualization _window_ if the software in question also requests to display itself on top of other applications like keyviz. Maybe that's what happens in your case. I'll recommend you to launch blender (without restarting) in _minimized_ mode and then see if the visualization was getting hidden.

Also, I've gone ahead and downloaded **blender 3.2**. And after opening blender, my keystrokes get visualized without any issue.

![image](https://user-images.githubusercontent.com/96373135/186348841-88c1e9e9-5b2e-4d79-b923-c83e93849a3d.png)
