### ISSUE TITLE
There should be an option for duration of the key appearing.

### ISSUE THREAD

**Issue by damywise** [mulaRahul/keyviz#4]
**Is your feature request related to a problem? Please describe.**
The appearance duration is too long for my personal preference.

**Describe the solution you'd like**
I would like for people to be able to set their desirable duration for the keys to appear. 

**Describe alternatives you've considered**
None

**Additional context**

**Comment by mulaRahul** [comment]
Added with the 5363983225af030fb017278113842441786197b2 commit!
