### ISSUE TITLE
plz add shortcut key SHIFT

### ISSUE THREAD

**Issue by xixikiller** [mulaRahul/keyviz#40]
Keyviz is very useful for Software Online Education, but in some software such as PowerPoint, SHIFT is a very useful and important shortcut key. Could you plz add it to the shortcut key list, let it be seen when pressed? That would be better! Thank you!

**Comment by xixikiller** [comment]
I mean ONLY press Shift, NOT Ctrl + Shift.

**Comment by mulaRahul** [comment]
By default, the <kbd>Shift</kbd> key and its combinations are ignored when the hotkey filter is turned on. Mostly shortcuts don't start with <kbd>Shift</kbd> instead its used for capitalization like <kbd>Shift</kbd> + <kbd>A</kbd>.

It'll be better to let the user decide about the same. I'll add an option under the hotkey filter, where you can choose to ignore or show <kbd>Shift</kbd> key.

**Comment by xixikiller** [comment]
> By default, the Shift key and its combinations are ignored when the hotkey filter is turned on. Mostly shortcuts don't start with Shift instead its used for capitalization like Shift + A.
> 
> It'll be better to let the user decide about the same. I'll add an option under the hotkey filter, where you can choose to ignore or show Shift key.

Thank you! Yes I know many shortcuts start with Ctrl, but in PowerPoint and many software includes drawing function, when I need to draw a horizontal or vertical line，when I need to draw a square instead of a rectangle, I must press and hold Shift. I want to show these to the audience in front of the screen.

**Comment by mulaRahul** [comment]
https://github.com/mulaRahul/keyviz/releases/tag/v2.0.0a
