### ISSUE TITLE
The DPI of my win7 is 125%. After the software is opened, the window displays abnormally

### ISSUE THREAD

**Issue by drw2005** [mulaRahul/keyviz#42]
**Describe the bug**
The DPI of my win7 is 125%. After the software is opened, the window displays abnormally. A black block is displayed on the right side of the solution. It cannot be closed, and the process can only be ended through the task manager.

**Version**: v0.x.x
1.06

**Desktop (please complete the following information):**
 - Windows 7

![QQ截图20220831093553](https://user-images.githubusercontent.com/33473981/187573784-97570de1-d3c3-4ab3-ba57-870e362e077c.png)

**Comment by damywise** [comment]
https://github.com/alexmercerind/flutter_acrylic/issues/26#issuecomment-1114308846:
The plugin `flutter_acrylic` does not support below Windows 10, so I guess no fix for this issue unless you upgrade to Windows 10 1803 or higher.

**Comment by drw2005** [comment]
> [alexmercerind/flutter_acrylic#26 (comment)](https://github.com/alexmercerind/flutter_acrylic/issues/26#issuecomment-1114308846): The plugin `flutter_acrylic` does not support below Windows 10, so I guess no fix for this issue unless you upgrade to Windows 10 1803 or higher.

Thanks.
