### ISSUE TITLE
[BUG] White rectangle shows in preview area

### ISSUE THREAD

**Issue by shirok1** [mulaRahul/keyviz#49]
**Describe the bug**
White rectangle shows in preview area.

**Version**: v1.0.4

**To Reproduce**
1. Go to settings
2. Click on any dropdown
3. Scroll down

**Expected behavior**
No such rectangle should be shown.

**Screenshots**
![gif](https://user-images.githubusercontent.com/12044683/188296831-e5e6adea-d40f-4cf0-9de7-d4043790f62a.gif)

**Desktop (please complete the following information):**
 - Windows 11

**Comment by mulaRahul** [comment]
https://user-images.githubusercontent.com/96373135/188302215-784f4320-ccce-4db8-8189-83f0c5298923.mp4


As you can see above I couldn't reproduce the bug. Maybe it is a rendering artifact. Does this happen every time or you've spotted it at a particular event?

**Comment by shirok1** [comment]
The white rectangle disappears when the mouse is clicked, try to scroll with your scroll wheel.

**Comment by mulaRahul** [comment]
![image](https://user-images.githubusercontent.com/96373135/188312268-707e078c-462f-4cc7-a97b-b19ecd5c0bbc.png)

Yea, now it's visible. Maybe the same isn't clipped due to some reason. Will have to look further into the same.

**Comment by mulaRahul** [comment]
https://github.com/mulaRahul/keyviz/releases/tag/v2.0.0a
