### ISSUE TITLE
Enhancements to settings window/page: "Don't Save" and "Reset Settings".

### ISSUE THREAD

**Issue by damywise** [mulaRahul/keyviz#5]
**Is your feature request related to a problem? Please describe.**
1. When closing the window, sometimes I would like to not save the changes I just made and just close the window/page because I only want to test the settings and I don't remember the original settings. Hence, the option for not saving ("Don't Save" button when closing the settings page/window).
2. Maybe I want to reset settings as you have preconfigured because I realized that I don't like what I have changed and want to reset. Hence, "Reset Settings" button. Maybe somewhere in the General tab.

**Describe the solution you'd like**
1. Add "Don't Save" button in the close confirmation window (when exiting settings page)
2. Add "Reset Settings" button in the General tab.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by mulaRahul** [comment]
@damywise  Sounds good! I will add them to the next release.

**Comment by mulaRahul** [comment]
Added with the 28da1eb611334eb8883f0e7aaa2c6bd4c2e43e3a and 130c7cf3b54dcebebed1ffc9e8a45eff2a16f9e0 commits!
