### ISSUE TITLE
Display multiple letters at a time

### ISSUE THREAD

**Issue by Zavijah** [mulaRahul/keyviz#55]
# Feature request
When I type in the word, like 'apple', I think Keyviz should display multiple letters at a time in 1-2 seconds instead of just one letter at a time.
I used Photoshop to create two images to show the difference between them.
## now:
![aaa](https://user-images.githubusercontent.com/76637811/190456261-5131c44a-9c42-40c1-8b7d-f6d6f065ca24.png)
## want:
![bbb](https://user-images.githubusercontent.com/76637811/190457321-f68e9b0e-98ac-49f2-8930-05ca6bbc450b.png)
# The end
I think Keyviz very good!

**Comment by Copy2Translator** [comment]
I don't think it's a good idea, it will cause you to display confusion when hitting the keyboard continuously.

**Comment by mulaRahul** [comment]
I can see where you're coming from but generally speaking, displaying letters together like that doesn't have practical requirements. As the visualization shows individual keys (for example <kbd>Ctrl</kbd>, <kbd>A</kbd>, <kbd>P</kbd>, <kbd>P</kbd>), changing to the above will break the consistency (like <kbd>Ctrl</kbd>, <kbd>APP</kbd> _where APP is displayed like a single key which isn't the case_). If you want to show some words like that, you'd already be typing the same either in a text field or another input field.
