### ISSUE TITLE
Conflict, F1 will be displayed until you exit Keyviz.

### ISSUE THREAD

**Issue by Copy2Translator** [mulaRahul/keyviz#57]
**Describe the bug**
Conflict with Snipaste screenshot software, when Snipaste hotkey F1 is pressed to take a screenshot, F1 hotkey will be displayed until you exit Keyviz.

This isn't much of a problem, it can be avoided by changing the Snipaste hotkeys, but I suppose there are other situations that would trigger something like this.

**Version**: 
Keyviz v1.0.6
Snipaster v2.7.3

**Desktop:**
 - Windows 10 LTSC 1809

**To Reproduce**
1. Open Snipaste
2. Presse F1 screenshot，F3 paste
3. See error

https://user-images.githubusercontent.com/75414580/190598089-1a290d9b-e253-4b69-9b54-2e218c764ee4.mp4

**Comment by mulaRahul** [comment]
The same has been already raised in issue #23. I've figured out that _due to some reason_ keyviz gets <kbd>F1</kbd> key ⬇️ **press event** but **isn't** followed by a key ⬆️ **release event** causing the visualization to be stuck like that. 

The same is caused when **Snipaste** is activated. You'll see its window covering the full-screen and at the same time, keystroke visualization getting hidden. I'll need to look further into the issue to find the cause.
