### ISSUE TITLE
Border Color option are reset

### ISSUE THREAD

**Issue by Copy2Translator** [mulaRahul/keyviz#58]
**Describe the bug**
The border color is set to transparent or dark gray and will be reset to silver when opened again after saving.

**Version**: v1.0.6

**Desktop (please complete the following information):**
 - Windows 10 LTSC 1809

https://user-images.githubusercontent.com/75414580/191666940-210480ba-da81-4a80-a7c1-60c6f6aadc59.mp4

**Comment by mulaRahul** [comment]
The same was caused due to the use of uppercase for some hex color codes -

https://github.com/mulaRahul/keyviz/blob/5363983225af030fb017278113842441786197b2/lib/data/properties.dart#L117-L120

The same is fixed by converting the hexcodes from uppercase to lowercase with 5361b2d.
