### ISSUE TITLE
can not show on the second screen

### ISSUE THREAD

**Issue by Excel880** [mulaRahul/keyviz#61]
this tools is very good! but I have a problem ,my computer have 2 screen , i want to show keytip on then second screen ,but now i just can show it on then primary sceen
![image](https://user-images.githubusercontent.com/11969964/201503178-95bacc2d-8cf7-4a02-9d18-2ccd55ed77ad.png)

**Comment by mulaRahul** [comment]
Multi-display support is planned for the next release, #36.
