### ISSUE TITLE
Size setting should have more options

### ISSUE THREAD

**Issue by ahmet-cetinkaya** [mulaRahul/keyviz#64]
**Is your feature request related to a problem? Please describe.**
More size options should be displayed.

**Describe the solution you'd like**
Instead of the size dropdown select menu, there may be a gradual slider input. And Users should be able to configure smaller than 32px.

**Describe alternatives you've considered**
The size dropdown menu should have more options smaller than 32px.

**Additional context**

**Comment by mulaRahul** [comment]
The same has been planned as per #14.
