### ISSUE TITLE
Screen choosing setting

### ISSUE THREAD

**Issue by ahmet-cetinkaya** [mulaRahul/keyviz#65]
**Is your feature request related to a problem? Please describe.**
Keystrokes don't appear on the second screen, for example.

**Describe the solution you'd like**
In addition to the alignment setting, must have a screen choosing setting.

**Describe alternatives you've considered**

**Additional context**

**Comment by mulaRahul** [comment]
**Multi-Display Support** is already planned for the next release #36.
