### ISSUE TITLE
Add Keyviz to package managers

### ISSUE THREAD

**Issue by sitiom** [mulaRahul/keyviz#67]
**Is your feature request related to a problem? Please describe.**
Hi, I plan to add Keyviz to both [Winget](https://learn.microsoft.com/en-us/windows/package-manager/) and [Scoop](https://scoop.sh/). However, Winget does not support extracting from zip files yet. Can you please provide the installer executable in the release assets directly? Thanks.

**Checklist**
- [x] Scoop (https://github.com/ScoopInstaller/Extras/pull/10002)
- [x] Winget (https://github.com/microsoft/winget-pkgs/pull/91471)

**Comment by mulaRahul** [comment]
Hello @sitiom, thanks for taking the time to extend keyviz with Winget and Scoop. As suggested in #48, I tried performing the same, but wasn't able to understand it well 😅.

As for adding the raw `.exe` in the releases folder, I haven't done that because currently it's not signed with any certificate which leads to a virus alert and the browser automatically stops the download. I've [planned](https://github.com/mulaRahul/keyviz/discussions/36#discussioncomment-4352731) on signing it in the upcoming release. But for now, I'll add the `.exe` to the releases folder.

**Comment by sitiom** [comment]
@mulaRahul Thanks! Here is the PR for Winget: https://github.com/microsoft/winget-pkgs/pull/91471.

The package would need to be updated every release in the case of Winget, as there isn't any built-in package update automation in the repo, unlike Scoop. So you would have to use something like the [Winget Releaser](https://github.com/vedantmgoyal2009/winget-releaser) on your repo. I can help in adding that once the PR is merged.

**Comment by sitiom** [comment]
https://github.com/microsoft/winget-pkgs/pull/91471#discussion_r1051117044

@mulaRahul Keyviz requires [VCRedist 2015-2022](https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist); you might want to add that to the README.

**Comment by mulaRahul** [comment]
Oh yeah, that's also mentioned in flutter [docs](https://docs.flutter.dev/development/platform-integration/windows/building#building-your-own-zip-file-for-windows), I'll add that to the README.
As the docs suggest, I should bundle the `.dll`'s with the application from the next release.

**Comment by sitiom** [comment]
@mulaRahul https://github.com/microsoft/winget-pkgs/pull/91471#pullrequestreview-1221780466
> Version is marketed as `1.0.6` but the version written to ARP/Registry is `1.0.7` (probably a small mistake in the installer). Should be brought up to the publisher to resolve this inconsistency before we accept it into WinGet.

Didn't notice it till now, but the executables inside the zip release assets are also named `1.0.7`. Can you fix this?

**Comment by mulaRahul** [comment]
Oh, I think I confused either the git-version or the build version. It should be 1.0.6, so will fix that.

**Comment by mulaRahul** [comment]
✅ Fixed!
