### ISSUE TITLE
Scoop Manifest

### ISSUE THREAD

**Issue by JustinGrote** [mulaRahul/keyviz#68]
Great utility! You should consider submitting a scoop manifest so that it is available to install via `scoop`
https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md

**Comment by mulaRahul** [comment]
Hello @JustinGrote, @sitiom is contributing the same #67!

**Comment by sitiom** [comment]
@mulaRahul Can you reopen my issue and close this one as a duplicate?

**Comment by mulaRahul** [comment]
Yea, that sounds alright!
