### ISSUE TITLE
Null key appears with shortcut

### ISSUE THREAD

**Issue by tunbk1002** [mulaRahul/keyviz#88]
**Describe the bug**
A `Null` key appears and can never be cleared when pressing <kbd>Alt</kbd>+<kbd>Shift</kbd>

**Version**: v1.0.6-portable

**To Reproduce**
1. Press <kbd>Alt</kbd>+<kbd>Shift</kbd> anywhere onscreen

**Expected behavior**
Any unrecognized key should be clear asap

**Screenshots**
![image](https://user-images.githubusercontent.com/50549524/211815341-0a1a7380-135e-478c-8e3b-6ea1495f2d87.png)
![image](https://user-images.githubusercontent.com/50549524/211815529-593ebd3c-543c-4750-b4b3-8f71a7e0085b.png)

**Desktop (please complete the following information):**
 - Windows 11

**Comment by mulaRahul** [comment]
Hello @tunbk1002, I cannot reproduce the above by just pressing <kbd>Alt</kbd>+<kbd>Shift</kbd> -

https://user-images.githubusercontent.com/96373135/212002368-d20a9519-f5c0-4494-9974-4f807d0e65ab.mp4

Maybe you're pressing another key after <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>?</kbd>, whose data isn't present hence <kbd>Null</kbd> is shown. If that's the case can you provide that as well? Also, your **General** settings will be helpful too.

**Comment by mulaRahul** [comment]
Hello @tunbk1002, can you reproduce the same with [v2.0.0a](https://github.com/mulaRahul/keyviz/releases/tag/v2.0.0a)?
